### ISSUE TITLE
IPTV data URL

### ISSUE THREAD

**Issue by waldenn** [shriram-k/iptv-viewer#3]
I think the data URL should be: https://iptv-org.github.io/api/channels.json
Instead of: https://iptv-org.github.io/iptv/index.nsfw.m3u (not available anymore)

The "playlistGenerator.js" script should be modified to parse this file.

**Comment by shriram-k** [comment]
It has been some time since I worked on this project. If you would like to see the changes immediately, Please go ahead and create a PR. If you want me to do it, I'll take a look at this by next week.

**Comment by waldenn** [comment]
Don't feel forced to do anything or do it soon. I'm still working on other things related to IPTV (such as creating an IPTV datasource for my Conzept project). I wanted to use your project as a channel "renderer". So take your time. Thanks!!

**Comment by shriram-k** [comment]
@waldenn There are inconsistencies between Channels API and Streams API. There are channels in Channels API which do not have an equivalent steam available on Streams API and vise versa. As an interim solution I've updated the scraped playlist to `https://iptv-org.github.io/iptv/index.m3u` which is currently available till I find a better solution.

**Comment by waldenn** [comment]
Thank you Shiram, works great!
